# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
    branches:
        - main
jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd angular-ci-cd-test
        npm ci
      continue-on-error: false   

    - name: Build Angular Project
      run: |
        cd angular-ci-cd-test 
        npx ng build
      continue-on-error: false   

    - name: Commit and push dist directory
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "lozano.roberto.2018@gmail.com"
            
        # Check if dist-history branch exists and if not create it
        git checkout dist-history || git checkout -b dist-history
            
        git add ./angular-ci-cd-test/dist/
        git commit -m "Adding dist for deployment on $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin dist-history


    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './angular-ci-cd-test/dist/angular-ci-cd-test/'
        production-branch: main
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1